dist: trusty
sudo: required

services:
  - docker
  
language: java

jdk:
    - openjdk8
    - oraclejdk8

addons:
  apt:
    packages:
    - libnetcdfc7
    - libgsl0ldbl
    - libudunits2-0

cache:
  directories:
  - $HOME/.m2
